// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieacaixnfgtfdngnsmln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllYWNhaXhuZmd0ZmRuZ25zbWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzgzMTQsImV4cCI6MjA2OTExNDMxNH0.yKm23OcBE1rL-U7OKUki8DGyStlJgveGiO0ElXoZS-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});